Prepare release 0.6.5
cloud-annotations/docusaurus-openapi pull request #268
Opened 2023-12-13 10:00 UTC by techwritermat

Preparing release 0.6.5 with Docusaurus 3.0 support.

2023-12-13 15:22 UTC, bourdakos1 requested changes
Since this is a breaking change, can we do 0.7.0 instead?

2023-12-13 15:22 UTC, bourdakos1 commented on .vscode/settings.json
Can we drop this change?

2023-12-13 15:38 UTC, techwritermat commented on .vscode/settings.json
Sure thing

2023-12-13 18:01 UTC, bourdakos1 approved these changes

2023-12-13 19:20 UTC, bourdakos1 commented
Can you update the PR title to pass the title check and resolve the lint issues?

2023-12-13 19:53 UTC, techwritermat commented
> Can you update the PR title to pass the title check and resolve the lint issues?

done boss

2023-12-13 23:17 UTC, bourdakos1 commented
Still looks like there’s a couple lint issues

2023-12-13 23:18 UTC, bourdakos1 commented
Not sure why these weren’t failing before, your PR doesn’t have any code changes :/

2023-12-14 06:38 UTC, techwritermat commented
> Not sure why these weren’t failing before, your PR doesn’t have any code changes :/

Yeah, it's weird. I ran prettier on the three files the linter complained about. Hopefully, that fixes it 🤞

2023-12-14 10:55 UTC, axel7083 commented
Wonderful jobs !

2023-12-14 15:34 UTC, merged